### ISSUE TITLE
Anki crashes with an error when using HoochiePapa in newer versions.

### ISSUE THREAD

**Issue by VincentOostelbos** [lovac42/HoochiePapa#11]
I believe this is from version 2.1.25 onward, but I'm not sure exactly, it might be later. It's certainly the case in 2.1.29, the newest version. This is the error message I get:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-02 00:58:13

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 490, in handler
  File "aqt\reviewer.py", line 320, in _onAnswerButton
  File "aqt\reviewer.py", line 261, in _answerCard
  File "aqt\reviewer.py", line 110, in nextCard
  File "lib\site-packages\anki\schedv2.py", line 62, in getCard
  File "lib\site-packages\anki\schedv2.py", line 258, in _getCard
  File "lib\site-packages\anki\schedv2.py", line 328, in _getNewCard
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-22>", line 2, in _fillNew
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
TypeError: fillNew() got multiple values for argument '_old'
```

I hope this can be fixed, because I really like this addon! I could of course downgrade to an earlier version, but I would rather not have to do that.

**Comment by TheAlmightyDada** [comment]
I am having this exact issue with Version 2.1.35
